name: Python Generate Pages

on:
  push:
    branches: ["main"]
    paths: ['**.json','**.md']

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate_page:
    runs-on: ubuntu-latest

    env:
      EMAIL: ${{ secrets.GIT_EMAIL }}
      USER: ${{ secrets.GIT_USER}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "America/Sao_Paulo"
          timezoneMacos: "America/Sao_Paulo"
          timezoneWindows: "America/Sao_Paulo"


      - name: prepare env
        run: |
          pip install --upgrade pip
          pip install markdown2

      - name: generate post
        if: ${{ contains(github.event_path, '.md') }}
        run: python3 scripts/py/generate_post_page.py
      
      - name: generate index
        run: python3 scripts/py/generate_index.py

      - name: commit and push HTML
        run: |
          git config --global user.email $EMAIL
          git config --global user.name $USER
          git pull
          git add .
          git commit -m "[actions] Generate HTML page"
          git push